### ISSUE TITLE
False address attack

### ISSUE THREAD

**Issue by huitema** [kazuho/draft-kazuho-quic-authenticated-handshake#7]
Even if the messages are perfectly sealed and protected, the attacker can still play games by racing duplicates that use a different source address than the actual peer address. How do we protect against that?

**Comment by kazuho** [comment]
Good point.

QUIC v1 simply states: _"Hosts try to associate a packet with an existing connection. If the packet has a Destination Connection ID corresponding to an existing connection, QUIC processes that packet accordingly."_ ([draft-ietf-quic-transport; section 5.2](
https://quicwg.org/base-drafts/draft-ietf-quic-transport.html#rfc.section.5.2)).

We should state that servers map Initial packets to connections using (CID, 5-tuple). Filed #10.

**Comment by huitema** [comment]
It really is complicated. Suppose the following:
```
Client                  Attacker                Server

CInitial ->
                        CInitial' ->
                        CInitial  ->
```
CInitial' is an exact copy of CInitial, the only difference is a bogus source address. I bet you that most stacks will just accept it, then treat the next packet as a duplicate.

The only protection against that in the toolkit is the "Retry Token", which proves ownership of the IP address. If CInitial carries a retry Token, then the attacker cannot spoof it. CInitial' will be rejected. But that supposes that the server actually drops packets that don't have a valid retry token, or maybe just sends a Retry. If the server does not do that, it will create a context indexed by the DCID, and never learn the real address. But then, look at the more complex scenario:

```
Client                  Attacker                Server

CInitial(A) ->
                        CInitial(A') ->
                                                     <- Retry(T(A'))
                        CInitial(A)  ->
                                                     <- Retry(T(A))
CInitial2(A, T(A)) -->
                       CInitial2(A',T(A'))->
                       CInitial2(A, T(A))->
```
The attacker copies the client's second Initial packet, but replaces address and token with the spoofed value A', and with the token that it learned in the server's response. How does the server know the difference?

It can only work if the server can distinguish between the "true" response and the spliced response. This probably implies checking the DCID sent by the client. The spec says that this is copied from the SCID of the retry packet: `The server includes a connection ID of its choice in the Source Connection ID field. This value MUST not be equal to the Destination Connection ID field of the packet sent by the client. The client MUST use this connection ID in the Destination Connection ID of subsequent packets that it sends.`

Let's assume that before sending the retry the server computes SCID= hash(Client Hello, Retry token). If the client resends the same CInitial, only changing the token, then it works. The server can verify that the DCID in CInitial2(A, T(A)) matches the hash, and that the DCID in CInitial2(A',T(A')) does not.
```

**Comment by kazuho** [comment]
@huitema 
> CInitial' is an exact copy of CInitial, the only difference is a bogus source address. I bet you that most stacks will just accept it, then treat the next packet as a duplicate.

Yes. That's what QUICv1 specifies. Though a stack can treat Initial packets arriving from different source addresses as different connections, because QUICv1 does not allow an endpoint to migrate during connection establishment.

> The only protection against that in the toolkit is the "Retry Token", which proves ownership of the IP address.

This is what I disagree.

Our threat model is that an attacker can inject packets but they cannot drop. The server will (eventually) receive an Initial packet with the correct source address.

Therefore, my view is that requiring the server to treat Initial packets coming from different addresses as belonging to different connections (even if DCID is the same) is enough.

**Comment by huitema** [comment]
I would like to have CID=hash(Client Hello| Retry Token). In case of Retry, the CID could be computed by the server who proposes it in the retry message. This prevents address swapping attacks, and I think is generally useful.

**Comment by kazuho** [comment]
I'm not sure if we should do that. IIUC, the intent of allowing the server-side to specify a different CID in Retry is to let a server node specify a particular server within the server cluster for processing the connection. To achieve that, the server that sends a Retry needs a free hand to select whatever CID it likes, instead of using a hash function for deriving the value.

PS. Therefore, what I am proposing in #8 is to use ODCID as the credential even after a Retry. The Initial sent in response to a Retry would use a server-supplied DCID but the cryptographic binder would continue to be Hash(Client Hello) (== ODCID). A server is required to be able to recover ODCID from the token anyways, so this is IMO a trivial change.

**Comment by huitema** [comment]
I was thinking about these issues and yes, I think using the ODCID after a retry is the key. When receiving an original Initial packet, check that DCID = hash(Initial content); if this is the retried Initial, check that ODCID=hash(Initial content).

This works on the server side because the server already needs to know the ODCID -- it has to echo it in the transport parameters extension. 

It requires some care on the client side, namely ensuring that when replying to a retry packet, the content of the new Initial is exactly the same as the original Initial. We need to specify that.

I agree that we don't need to use the tokens to compute the CID. The attack that I was describing above is not possible. I wrote:
```
Client                  Attacker                Server

CInitial(A) ->
                        CInitial(A') ->
                                                     <- Retry(T(A'))
                        CInitial(A)  ->
                                                     <- Retry(T(A))
CInitial2(A, T(A)) -->
                       CInitial2(A',T(A'))->
                       CInitial2(A, T(A))->
```
... but the splicing of an attacker token to the client's Initial is not possible. The Token is part of the packet header and is authenticated by the HMAC. The HMAC cannot be computed without knowing the ESNI secret, which means the attacker cannot do that.

So we are good. The Retry/Token mechanism prevents messing with the addresses; the ESNI-dependent HMAC prevents attackers from replacing the tokens; and the DCID/ODCID checks seal the Initial.

**Comment by huitema** [comment]
Actually, this is a bit more complicated. Consider the following:
```
Client                  Attacker                Server

CInitial(A) ->
                        CInitial(A') ->
                                                <- Retry(T(A'))
                        CInitial(A)  ->
                                                <- Retry(T(A))

                        
                        <- Retry(T(A'))
                        <- Retry(T(A))
```
The attacker sends a copy of the original CInitial, with an attacker chosen source address A'. The server (or the firewall in front of the server) generates different retry packets for each of the received initials. The attacker receives its own token, and forward the retry packet to the client. The client will receive two retry packets. If it accepts the first one, the attacker can intercept the first reply, recognize that it bears its own token, and send it:
```
Client                  Attacker                Server

                        <- Retry(T(A'))
                        <- Retry(T(A))
CInitial2(T(A'), A) ->
                        CInitial2(T(A'), A') ->
                                                 Creates connection with ODCID
                        CInitial2(T(A'), A) ->
                                                 Ignore as it fails address verification
CInitial2(T(A), A) ->
                                                 Ignore as duplicate
```
The server's connection is with the attacker's address. The attacker can fail the connection.

**Comment by huitema** [comment]
Bottom line, the only defense is to create separate connection contexts for each pair of (CInitial, client address)

**Comment by kazuho** [comment]
@huitema I agree with your analysis.

> It requires some care on the client side, namely ensuring that when replying to a retry packet, the content of the new Initial is exactly the same as the original Initial. We need to specify that.

We have that: _"Payload of the CRYPTO frame contained in the resent Initial packets MUST be identical to that of the Initial packet that triggered the retry."_
